require "plugins.plugin-config.nvim-cmp"
require "plugins.plugin-config.mason-lsp"
require "plugins.plugin-config.telescope"
require "plugins.plugin-config.treesitter"
require "plugins.plugin-config.dashboard"
